---
- name: Pull docker image DevOpsCalculator
  hosts: localhost
  tasks:
    - name: Pull docker image DevOpsCalculator
      docker_image:
        name: shrey15/devopscalculator
        source: pull